travis:
  secure:
    BINSTAR_TOKEN: PxqiTmVC8NuDZkYCgUMjsJl6atm02rCDztB8QqEmaSryBpvONsEnhUlb+0n9iv/BOKMyMvvOkP5+dOMxRxsNWZtj+ajRzJ5g39tkZpwHQeyYPVGn1B5qfOsyL8tBm/FjE0Kpd1l5O77QUZHVafUDLdlKzNgq6ppZmCu9RUkZU32KeSiZ4pR7Iy6nXuX1XxJbZx0W9kQ2f2b1v6iyu+iB2n16cleIMjxtsqF0j3Ddoib6dtvgFtN/0ibSb09IddoVSCbCQtGhfztY5rgEXkIfRDwfyg4b5twJ4bj0XL79qsdAmNjVsbWe+/Wl5WbIKBoJEezbf8tXavsG9dIDRc9zTKH7pdsRdgBYyO47I5M9wGPQ/4HNyhgUn5zPjQVLVJO7gkAzOCgl9d6QVfTXWor7ewwVSxoJ2xNaLuA0UMRF1QvDJ2plQDjaoaGT4eWsf44871b092sap7O25UcC4k4228NI7o1qjl8mUBfWB5Ilw6PByD4hr9cjCaGEVnM56WBGVG7zPDjfr0hY83mxheocGu6t/z8ijIKbQnrbL7B0nbKNu/4EHbEoYbE0SClB+S9DXK+XxiMLhi6OXpCglB0zCpOpKS/icd0Sog7kmyDQNbKiVnarcCQo1UkN8EDQcEGLW4bHXKrOCPTNxII0SJpOsnrSp7xiPgB8y3dFp8MWcjI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
