travis:
  secure:
    BINSTAR_TOKEN: IoJqOTNcl4/L+bH9WeDzqABGafQigMzJ5wgBTKCdfPW4V+hE6MovZiOrepAQNhhT9ivFju7WCgBDgcIijSlGRkUGT9rucdDbxf/YQSRC6d4DPjzghspuB6m5MyAuRYGsCT4qyygglal6/JltwxEDaHnsMHVi4taTPwTxVyEUNdgyCTXYyHX0taRWfGWDcJF9SqRI+zCg/X1tqpqZIalbax7Gahua9vGyjCmTMsdp0vmj38A0DF/16tfNG1WXNNNUNRcJy/eL68zSJvwjVOf8o0mNyb4ReYUryYBoL4VelxTFY+3+5crXLpAOs1ObK/QTmMmE3lEbI/ySRC0rCKUet1kiqX/HMG5kp1qKfwKnV4l6K50RCuDf8MfYjAkrnWOENnCsS8jsOPi2wbU+XSAG+XnfLQXSdfTN+JFO20g7UyguVyC1eEm4O0Z/U+vYNZf3USg/oM4SovbMogSQ4IOugcMYkHMKvGUnpmfd9lMVe8C+vmSqAI/qaVp0LGfO4SlpL6bcq4z5Da0CwNOFtdb0NjJ948/G0GVzwobzYW/VVXz2yykxrOH4OGQYpJ7UjnamrN6ZgrJRuWpTLbOLpYqnel/R9x78d5aD+4jQpXpznyA59/F29sT8DvLGFYdmmOvOO/gKbnpy6ybNVowptnLcwPUCNbcZMnuQiIoI+e0s7xw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
